/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Prayer = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'text' : IDL.Text,
  'translation' : IDL.Text,
  'category' : IDL.Text,
});
export const Ritual = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'steps' : IDL.Vec(IDL.Text),
});
export const FavoriteItem = IDL.Record({
  'id' : IDL.Nat,
  'itemType' : IDL.Text,
});
export const ScheduleItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'time' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFavorite' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getAllPrayers' : IDL.Func([], [IDL.Vec(Prayer)], ['query']),
  'getAllRituals' : IDL.Func([], [IDL.Vec(Ritual)], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(FavoriteItem)], ['query']),
  'getFullSchedule' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
  'getPrayerCompletionsForDate' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getPrayersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
  'markPrayerCompleted' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'removeFavorite' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Prayer = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'text' : IDL.Text,
    'translation' : IDL.Text,
    'category' : IDL.Text,
  });
  const Ritual = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'steps' : IDL.Vec(IDL.Text),
  });
  const FavoriteItem = IDL.Record({ 'id' : IDL.Nat, 'itemType' : IDL.Text });
  const ScheduleItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'time' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addFavorite' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllPrayers' : IDL.Func([], [IDL.Vec(Prayer)], ['query']),
    'getAllRituals' : IDL.Func([], [IDL.Vec(Ritual)], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(FavoriteItem)], ['query']),
    'getFullSchedule' : IDL.Func([], [IDL.Vec(ScheduleItem)], ['query']),
    'getPrayerCompletionsForDate' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getPrayersByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Prayer)], ['query']),
    'markPrayerCompleted' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'removeFavorite' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };