/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FavoriteItem { 'id' : bigint, 'itemType' : string }
export interface Prayer {
  'id' : bigint,
  'title' : string,
  'text' : string,
  'translation' : string,
  'category' : string,
}
export interface Ritual {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'steps' : Array<string>,
}
export interface ScheduleItem {
  'id' : bigint,
  'name' : string,
  'time' : string,
  'description' : string,
}
export interface _SERVICE {
  'addFavorite' : ActorMethod<[bigint, string], undefined>,
  'getAllPrayers' : ActorMethod<[], Array<Prayer>>,
  'getAllRituals' : ActorMethod<[], Array<Ritual>>,
  'getFavorites' : ActorMethod<[], Array<FavoriteItem>>,
  'getFullSchedule' : ActorMethod<[], Array<ScheduleItem>>,
  'getPrayerCompletionsForDate' : ActorMethod<[string], Array<bigint>>,
  'getPrayersByCategory' : ActorMethod<[string], Array<Prayer>>,
  'markPrayerCompleted' : ActorMethod<[bigint, string], undefined>,
  'removeFavorite' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];